#!/bin/bash
# Config the environment 


npm install @azure/event-hubs --save
git clone https://github.com/Azure/azure-event-hubs-node
cd az*
cd client

npm i
npm run build

echo "Initialize ran succesfully. Configure the .env now, then run produce"
